const ADD_TREE = "ADD_TREE"
const REMOVE_TREE = "REMOVE_TREE"
const FETCH_TREES = "FETCH_TREES"
const DATABASE_SAVING = "DATABASE_SAVING"
const DATABASE_INSPECTING = "DATABASE_INSPECTING"
const ERROR = "ERROR"
const LOADING_DATA = "LOADING_DATA"
const AUTHENTICATED = 'AUTHENTICATED'
const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'

export {ADD_TREE, REMOVE_TREE,FETCH_TREES, DATABASE_INSPECTING, LOADING_DATA, DATABASE_SAVING, ERROR, AUTHENTICATED, NOT_AUTHENTICATED}